# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: nealmind's Blog
email: nealriver@163.com
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://localhost:4000"
url: "https://nealmind.github.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:year/:month/:day/:title/

description_footer:
twitter_username: 
github_username:

# GitTalk
gitalk:
  enable: true
  clientID: a5fd9f069280008d197d
  clientSecret: 46d3a70fd16c3ab5c3078a869151e4f2d6b3e30b
  repo: blog-comments
  owner: nealmind
  admin: nealmind
  distractionFreeMode: true

# Build settings
markdown: kramdown

kramdown: 
  input: GFM
  syntax_highlighter: rouge

# url
category_dir: category/
tag_dir: tag/

# excerpt 摘要分割符，4个回车
excerpt_separator: "\n\n\n\n"

# paginate
plugins:
  - jekyll-paginate
paginate: 10